<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MediaPlayer_X_Ark</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject>MediaPlayer_X_Ark.Program</StartupObject>
    <PlatformTarget>x64</PlatformTarget>
    <Authors>Aoi.Kagase</Authors>
    <AssemblyName>x-ark</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="resources\Skins\Temp\**" />
    <EmbeddedResource Remove="resources\Skins\Temp\**" />
    <None Remove="resources\Skins\Temp\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="resources\fmod.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Mathf.cs" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
</Project>