<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MediaPlayer_X_Ark</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject>MediaPlayer_X_Ark.Program</StartupObject>
    <PlatformTarget>x64</PlatformTarget>
    <Authors>Aoi.Kagase</Authors>
    <AssemblyName>x-ark</AssemblyName>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <DebugType>embedded</DebugType>
    <SignAssembly>False</SignAssembly>
    <IsPublishable>True</IsPublishable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Resources\Skins\Temp\**" />
    <EmbeddedResource Remove="Resources\Skins\Temp\**" />
    <None Remove="Resources\Skins\Temp\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\fmod.dll" />
    <Content Include="Resources\Skins" />
	<Content Include="Resources\Plugins" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Mathf.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy Resources\* $(OutDir)\" />
  </Target>
</Project>